In [45]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [77]:
# load data from csv file
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [78]:
## Preprocessing the data
# drop unnecessary columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
# encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [79]:
## One-hot encode 'Geography' column
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geo = OneHotEncoder()
geo_encoded = one_hot_encoder_geo.fit_transform(data[['Geography']])
geo_encoded
# one_hot_encoder_geo.get_feature_names_out(['Geography'])
geo_encoded_df = pd.DataFrame(geo_encoded.toarray(), columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))

In [80]:
## Combine the one-hot encoded columns with the original dataframe
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [81]:
## Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)
with open('one_hot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder_geo, file)

In [82]:
data.isnull().sum()

CreditScore          0
Gender               0
Age                  0
Tenure               0
Balance              0
NumOfProducts        0
HasCrCard            0
IsActiveMember       0
EstimatedSalary      0
Exited               0
Geography_France     0
Geography_Germany    0
Geography_Spain      0
dtype: int64

In [83]:
## Divide the data into features and target variable
X = data.drop('Exited', axis=1)
y = data['Exited']

## Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)

## Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [85]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [86]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

ANN Implementation and training code will go here

In [87]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [88]:
## Build Our ANN model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)), ## HL1 Connected with input layer
    Dense(32, activation='relu'), ## HL2
    Dense(1, activation='sigmoid') ## Output layer
])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 64)                832

 dense_7 (Dense)             (None, 32)                2080

 dense_8 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [89]:
import tensorflow as tf
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)


model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

In [90]:
## Set up TensorBoard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [91]:
## Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [92]:
### Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=32,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 [==============================] - 3s 7ms/step - loss: 0.3973 - accuracy: 0.8300 - val_loss: 0.3613 - val_accuracy: 0.8500
Epoch 2/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3540 - accuracy: 0.8550 - val_loss: 0.3386 - val_accuracy: 0.8635
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3473 - accuracy: 0.8549 - val_loss: 0.3388 - val_accuracy: 0.8650
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3446 - accuracy: 0.8605 - val_loss: 0.3448 - val_accuracy: 0.8595
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3409 - accuracy: 0.8610 - val_loss: 0.3424 - val_accuracy: 0.8625
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3364 - accuracy: 0.8606 - val_loss: 0.3483 - val_accuracy: 0.8535
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3350 - accuracy: 0.8620 - val_loss: 0.3465 - val_accuracy: 0.8595
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3329 - accuracy: 0.8627 - val_loss: 0.3471 - val_accuracy: 0.8575
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3303 - accuracy: 0.8645 - val_loss: 0.3388 - val_accuracy: 0.8610
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3312 - accuracy: 0.8625 - val_loss: 0.3501 - val_accuracy: 0.8595
Epoch 11/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3271 - accuracy: 0.8645 - val_loss: 0.3503 - val_accuracy: 0.8615
Epoch 12/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3270 - accuracy: 0.8645 - val_loss: 0.3423 - val_accuracy: 0.8650

In [93]:
model.save('churn_model.h5')

c:\Users\ckumar2\OneDrive - Deloitte (O365D)\Documents\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [109]:
pip install tensorflow tensorboard

Requirement already satisfied: tensorflow in .\venv\Lib\site-packages (2.15.0)
Requirement already satisfied: tensorboard in .\venv\Lib\site-packages (2.15.2)
Requirement already satisfied: tensorflow-intel==2.15.0 in .\venv\Lib\site-packages (from tensorflow) (2.15.0)
Requirement already satisfied: absl-py>=1.0.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.16.0)
Requirement already satisfied: libclang>=13.0.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.2.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.26.4)
Requirement already satisfied: opt-einsum>=2.3.2 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.4.0)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (4.25.9)
Requirement already satisfied: setuptools in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (82.0.1)
Requirement already satisfied: six>=1.12.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (4.15.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.14.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.31.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.80.0)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in .\venv\Lib\site-packages (from tensorboard) (2.53.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in .\venv\Lib\site-packages (from tensorboard) (1.4.0)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard) (3.10.2)
Requirement already satisfied: requests<3,>=2.21.0 in .\venv\Lib\site-packages (from tensorboard) (2.34.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: pyasn1-modules>=0.2.1 in .\venv\Lib\site-packages (from google-auth<3,>=1.6.3->tensorboard) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in .\venv\Lib\site-packages (from google-auth<3,>=1.6.3->tensorboard) (48.0.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in .\venv\Lib\site-packages (from google-auth-oauthlib<2,>=0.5->tensorboard) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard) (3.16)
Requirement already satisfied: urllib3<3,>=1.26 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorboard) (2026.5.20)
Requirement already satisfied: wheel<1.0,>=0.23.0 in .\venv\Lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.15.0->tensorflow) (0.46.3)
Requirement already satisfied: cffi>=2.0.0 in .\venv\Lib\site-packages (from cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard) (2.0.0)
Requirement already satisfied: pycparser in .\venv\Lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in .\venv\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard) (0.6.3)
Requirement already satisfied: oauthlib>=3.0.0 in .\venv\Lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard) (3.3.1)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [110]:
tensorboard --version

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [111]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [112]:
%tensorboard --logdir logs/fit

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [ ]:
%reload_ext tensorboard
%tensorboard --logdir ./logs/fit